# Publish the static Sphinx build on Trading Strategy server using rsync

name: Docs build

on:
  push:
    branches: [ master ]
jobs:
  rsync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # We need to use HTTPS checkout on CI
      - name: Fetch submodules
        run: |
          git submodule set-url deps/furo https://github.com/tradingstrategy-ai/furo.git
          git submodule set-url deps/trade-executor https://github.com/tradingstrategy-ai/trade-executor.git 
          git submodule update --init --recursive
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        # If caches were enabled, it was caching Python 3.8 interpreter
        # causing the docs build to fails
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt-get install -y pandoc
          poetry env use '3.9'
          poetry install -vv
      - name: Build documentation
        run: |        
          poetry env use '3.9'
          python -V
          which python
          echo $PATH
          PYTHON=`poetry env info -p`/bin/python
          SPHINX=`poetry env info -p`/bin/sphinx-build
          make install-furo rebuild-furo html

      # https://zellwk.com/blog/github-actions-deploy/
      # https://github.com/webfactory/ssh-agent
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          # PK key pair generated locally and
          # public SSH key copied to the server
          ssh-private-key: ${{ secrets.RSYNC_KEY }}
      - name: Publish docs via rsync
        run: |
          $RSYNC_COMMAND
        env:
          # RSYNC_COMMAND="scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r docs/build/html docs@poly:."
          RSYNC_COMMAND: ${{ secrets.RSYNC_COMMAND }}


